modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/CAS-ual-TY/GunCus/issues"

[[mods]]
    modId="guncus"
    version="${file.jarVersion}"
    displayName="Gun Customization: Infinity"
    displayURL="https://github.com/CAS-ual-TY/GunCus"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team"
    authors="CAS_ual_TY"
    description="Tons of guns, attachments and combinations."
